export const REQUEST_STATUSES = {
  NEW: 1,
  ACTIVE: 2,
  CLOSE: 3
}

export const REQUEST_STATUS_NAMES = {
  [REQUEST_STATUSES.NEW]: 'Новое',
  [REQUEST_STATUSES.ACTIVE]: 'Активное',
  [REQUEST_STATUSES.CLOSE]: 'Закрытое'
}

export const SOCKET_EVENTS = {
  MESSAGE_CREATED: 'MESSAGE_CREATED',
  MESSAGE_DELETED: 'MESSAGE_DELETED',
  MESSAGE_UPDATED: 'MESSAGE_UPDATED',
  FILE_UPLOADED: 'FILE_UPLOADED'
}

export const MAX_FILES_COUNT_IN_MESSAGE = 10
