version: '3.7'

services:
  xxx:
    container_name: xxx
    image: node:lts-alpine
    restart: always
    working_dir: /var/www
    command: yarn prod
    volumes:
      - ./:/var/www:cached
    ports:
      - "9090:3000"
