version: '3.7'

services:
  nextjs_ts:
    container_name: nextjs_ts
    image: node:lts-alpine
    restart: always
    working_dir: /var/www
    command: yarn stage
    volumes:
      - ./:/var/www:cached
    ports:
      - "30000:3000"