version: '3.7'

services:
  web:
    build: .
    command: yarn serve
    ports:
      - 8080:8080

  cypress:
    image: cypress/included:9.7.0
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:8080
    working_dir: /e2e
    volumes:
      - ./:/e2e